Repository qdm12/gluetun, pull requests merged in 2024-08, with the labels that each got.

#2285 feat(privatevpn): support natively port forwarding
  README.md
  internal/configuration/settings/portforward.go
  internal/portforward/loop.go
  internal/portforward/service/settings.go
  internal/provider/privatevpn/portforward.go
  internal/provider/privatevpn/portforward_test.go
  internal/vpn/tunnelup.go
Labels: Status: 🗯️ Waiting for feedback

#2411 fix(firewall): delete chain rules by line number
  internal/firewall/delete.go
  internal/firewall/delete_test.go
  internal/firewall/interfaces.go
  internal/firewall/ip6tables.go
  internal/firewall/iptables.go
  internal/firewall/list.go
  internal/firewall/list_test.go
  internal/firewall/logger.go
  internal/firewall/mocks_generate_test.go
  internal/firewall/mocks_test.go
  internal/firewall/parse.go
  internal/firewall/parse_test.go
  internal/firewall/runner_mock_test.go
  internal/firewall/support_test.go
Labels: Priority: 🚨 Urgent

#2416 feat(settings): add storage filepath settings
  Dockerfile
  cmd/gluetun/main.go
  internal/configuration/settings/provider.go
  internal/configuration/settings/serverselection.go
  internal/configuration/settings/settings.go
  internal/configuration/settings/storage.go
  internal/configuration/settings/vpn.go
Labels: Status: 🟡 Nearly resolved
